name: PlatformIO Test and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run PlatformIO tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Build and test with PlatformIO
        run: |
          platformio test --environment native

  create_firmware_image:
    name: Create firmware image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Create firmware image
        run: |
          platformio run --environment target_run
          
      - name: Archive firmware image
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: .pio/build/target_run/firmware.hex

  create_flash_exe:
    name: Create and upload flash executable
    runs-on: windows-latest
    needs: create_firmware_image
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          # Additional setup commands as needed

      - name: Build Executable
        working-directory: artifact-builder/flash.bat
        run: |
          pyinstaller --onefile flash.bat
          # Add commands to package the files into an executable
          # or use NSIS to create an installer

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: flash-executable
          path: dist/flash.exe  # Adjust the path to the generated executable
