name: PlatformIO Test and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run PlatformIO tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Build and test with PlatformIO
        run: |
          platformio test --environment native
  create_firmware_image:
    name: Create firmware image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Create firmware image
        run: |
          platformio run --environment target_run
          
      - name: Archive firmware image
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            .pio/build/*/firmware.hex
            lib/
            test/
            platformio.ini
