name: PlatformIO mock test and Target_run compile

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run PlatformIO tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Build and test with PlatformIO
        run: |
          platformio test --environment native
          
  create_firmware_image:
    name: Create firmware image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Test target_run compilation
        run: |
          platformio run --environment target_run
