name: PlatformIO Test and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run PlatformIO tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Build and test with PlatformIO
        run: |
          platformio test --environment native

  release:
    name: Create and Release Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Convert repository name to lowercase and save to environment file
        run: echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get lowercase owner name and save to environment file
        run: echo "OWNER_NAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ env.OWNER_NAME }}/${{ env.REPO_NAME }}:latest .
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ env.OWNER_NAME }} --password-stdin
      
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag ghcr.io/${{ env.OWNER_NAME }}/${{ env.REPO_NAME }}:latest ghcr.io/${{ env.OWNER_NAME }}/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ env.OWNER_NAME }}/${{ env.REPO_NAME }}:latest
